[package]
name = "WirelessDisplay"
version = "0.1.0"
edition = "2024"
homepage = "https://github.com/teamclouday/wireless-display"

[dependencies]
anyhow = "1.0.99"
tokio = { version = "1.47.1", features = ["full"] }

dialoguer = "0.12.0"
clap = { version = "4.5.47", features = ["derive"] }

webrtc = "0.13.0"
base64 = "0.22.1"

warp = { version = "0.4.2", features = ["server"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"

xcap = "0.7.0"
ffmpeg-next = { version = "8.0.0", features = ["default"] }
